FROM docker:24.0.6-dind
#ARG USER ${USER}
#ARG USER_UID ${USER_UID}
#ARG USER_GID ${USER_GID}
ARG DOCKER_HUB_USER
ARG DOCKER_HUB_PASSWORD
ARG REGISTRY_MENDER_IO_USER
ARG REGISTRY_MENDER_IO_PASSWORD
ARG GITLAB_USER
ARG GITLAB_PAT

RUN apk --update add \
      bash \
      git \
      py-pip \
      gcc \
      make \
      libc-dev \
      libffi-dev \
      openssl-dev \
      python3 \
      curl \
      jq \
      sysstat \
      xz

#RUN addgroup -S --gid $USER_GID $USER \
#    && adduser -S --uid $USER_UID -G $USER --shell /bin/bash $USER

#USER ${USER}

ADD loop_set_version_and_repo.sh /opt/loop_set_version_and_repo.sh
ADD run_test_suite.sh /opt/run_test_suite.sh

RUN wget https://raw.githubusercontent.com/mendersoftware/integration/master/extra/requirements.txt \
      && pip3 install -r requirements.txt

RUN --mount=type=secret,id=docker_hub_password,target=/run/secrets/docker_hub_password \
      --mount=type=secret,id=registry_mender_io_password,target=/run/secrets/registry_mender_io_password \
      --mount=type=secret,id=gitlab_pat,target=/run/secrets/gitlab_pat \
      cat /run/secrets/docker_hub_password \
        | docker login \
          --username ${DOCKER_HUB_USER:-menderbuildsystem} \
          --password-stdin \
      && cat /run/secrets/registry_mender_io_password \
        | docker login \
          --username ${REGISTRY_MENDER_IO_USER:-ntadm_menderci} \
          --password-stdin \
          registry.mender.io \
      && cat /run/secrets/gitlab_pat \
        | docker login \
          --username ${GITLAB_USER} \
          --password-stdin \
          registry.gitlab.com

# skip cache if the repos have been updated
ADD "https://api.github.com/repos/mendersoftware/mender-qa/commits?per_page=1" latest_commit_mender_qa
ADD "https://api.github.com/repos/mendersoftware/integration/commits?per_page=1" latest_commit_integration

RUN git clone --depth 1 https://github.com/mendersoftware/mender-qa.git \
      && cd mender-qa \
      && git clone --depth 1 https://github.com/mendersoftware/integration.git

ENTRYPOINT ["dockerd-entrypoint.sh"]
